name: Close Issue on Pull Request Close

on:
  pull_request:
    types: [closed]

jobs:
  close-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Close Issue
      if: github.event.pull_request.merged == false && github.event.pull_request.closed_at != null
      uses: peter-evans/close-issue@v1.0.0
      with:
        issue-number: ${{ github.event.pull_request.title | replace("(#| )", "") }}
        comment: 'This issue has been closed because the corresponding pull request has been closed.'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
